Fix stream_encode_multipart
There was an error. How to reproduce it:
Try to create a request having both plain and file-like objects in it,
like this:

myfile = open('/dev/null')
EnvironBuilder(data=dict(
    id=123,
    somefile=(myfile, 'empty_file.txt'),
))

Expected result: request is built
Actual result: we get an error:

(...)
env/lib/python3.5/site-packages/werkzeug/test.py:106: in stream_encode_multipart
    write_binary(value)
env/lib/python3.5/site-packages/werkzeug/test.py:59: in write_binary
(string = '123')
                stream.write(string)
TypeError: a bytes-like object is required, not 'str'

As you can see, without this fix non-string values are converted to string,
but then are passed to method which expects only bytes.